# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'PostsManagerApp' do
  use_frameworks!
  
  pod 'Alamofire', '4.9'
  pod 'AlamofireObjectMapper'
  pod 'ObjectMapper'
  pod 'RealmSwift'
  
end
