# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

use_frameworks!
target 'PostsManagerApp' do
  
  pod 'Alamofire', '4.9'
  pod 'AlamofireObjectMapper'
  pod 'ObjectMapper'
  pod 'RealmSwift'
  
end
